const CONFIG = {
    whatsappNumber: "56982622961",
    storeName: "SpinRemates",
    currency: "$",
};

const ITEMS = [
    {
        id: "fig-001",
        category: "mdf",
        name: "Cenicienta",
        image: "Figuras Mdf/Cenicienta 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-002",
        category: "mdf",
        name: "flaco",
        image: "Figuras Mdf/flaco.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "???",
        height: "???",
        sold: false
    },
    {
        id: "fig-003",
        category: "mdf",
        name: "Gaby",
        image: "Figuras Mdf/Gaby 90 cm $ 11.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 11500,
        salePrice: 8050,
        width: "90 cm",
        height: "90 cm",
        sold: false
    },
    {
        id: "fig-004",
        category: "mdf",
        name: "gata",
        image: "Figuras Mdf/gata 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-005",
        category: "mdf",
        name: "hada",
        image: "Figuras Mdf/hada 60 cm $ 6.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 6500,
        salePrice: 4550,
        width: "60 cm",
        height: "60 cm",
        sold: false
    },
    {
        id: "fig-006",
        category: "mdf",
        name: "Looney Tunes",
        image: "Figuras Mdf/Looney Tunes 50 cm $ 5.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 5500,
        salePrice: 3850,
        width: "50 cm",
        height: "50 cm",
        sold: false
    },
    {
        id: "fig-007",
        category: "mdf",
        name: "podium",
        image: "Figuras Mdf/podium 50 cm $ 5.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 5500,
        salePrice: 3850,
        width: "50 cm",
        height: "50 cm",
        sold: false
    },
    {
        id: "fig-008",
        category: "mdf",
        name: "Princesa Bella",
        image: "Figuras Mdf/Princesa Bella 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-009",
        category: "mdf",
        name: "Rapunzel",
        image: "Figuras Mdf/Rapunzel 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-010",
        category: "mdf",
        name: "roblox",
        image: "Figuras Mdf/roblox 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-011",
        category: "mdf",
        name: "Rumi",
        image: "Figuras Mdf/Rumi 70 cm $ 7.500.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 7500,
        salePrice: 5250,
        width: "70 cm",
        height: "70 cm",
        sold: false
    },
    {
        id: "fig-012",
        category: "mdf",
        name: "Zoey",
        image: "Figuras Mdf/Zoey 96 cm $ 15.000.jpg",
        description: "Figura decorativa en MDF.",
        originalPrice: 15000,
        salePrice: 10500,
        width: "96 cm",
        height: "96 cm",
        sold: false
    },
    {
        id: "tela-013",
        category: "telas",
        name: "Guerreras",
        image: "Telas Sublimadas/Guerreras 80x200 lateral $ 10.000.jpeg",
        description: "Tela sublimada premium.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "80 cm",
        height: "200 cm",
        sold: false
    },
    {
        id: "tela-014",
        category: "telas",
        name: "Kpop",
        image: "Telas Sublimadas/Kpop Lateral 80x200 $ 10.000.jpeg",
        description: "Tela sublimada premium.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "80 cm",
        height: "200 cm",
        sold: false
    },
    {
        id: "tela-015",
        category: "telas",
        name: "Kpop",
        image: "Telas Sublimadas/Lateral Kpop 80x200 $ 10.000.jpeg",
        description: "Tela sublimada premium.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "80 cm",
        height: "200 cm",
        sold: false
    },
    {
        id: "tela-016",
        category: "telas",
        name: "Plim Plim",
        image: "Telas Sublimadas/Lateral Plim Plim 80x200 $ 10.000.jpeg",
        description: "Tela sublimada premium.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "80 cm",
        height: "200 cm",
        sold: false
    },
    {
        id: "tela-017",
        category: "telas",
        name: "PlimPlim",
        image: "Telas Sublimadas/PlimPlim 80x200 lateral $ 10.000.jpeg",
        description: "Tela sublimada premium.",
        originalPrice: 10000,
        salePrice: 7000,
        width: "80 cm",
        height: "200 cm",
        sold: false
    }
];
